/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(audio_file_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6028cc2f19e9e14410c58a2894cd43a1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <tools/audio_file_source.h>
// pydoc.h is automatically generated in the build directory
#include <audio_file_source_pydoc.h>

void bind_audio_file_source(py::module& m)
{

    using audio_file_source    = gr::tools::audio_file_source;


    py::class_<audio_file_source, gr::sync_block,
              gr::block, gr::basic_block,
        std::shared_ptr<audio_file_source>>(m, "audio_file_source", D(audio_file_source))

        .def(py::init(&audio_file_source::make),
           py::arg("file_name"),
           py::arg("samp_rate_out"),
           py::arg("channels") = 1,
           py::arg("loop") = true,
           py::arg("normalize") = false,
           D(audio_file_source,make)
        )
        



        ;




}








