/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fm_modulator_fc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5f732e2abb7148b6a8161cbdce95e538)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <tools/fm_modulator_fc.h>
// pydoc.h is automatically generated in the build directory
#include <fm_modulator_fc_pydoc.h>

void bind_fm_modulator_fc(py::module& m)
{

    using fm_modulator_fc    = gr::tools::fm_modulator_fc;


    py::class_<fm_modulator_fc, gr::sync_block,
              gr::block, gr::basic_block,
        std::shared_ptr<fm_modulator_fc>>(m, "fm_modulator_fc", D(fm_modulator_fc))

        .def(py::init(&fm_modulator_fc::make),
           py::arg("samp_rate"),
           py::arg("freq_deviation"),
           py::arg("initial_phase"),
           D(fm_modulator_fc,make)
        )
        



        ;




}








